# Generated by Django 5.2.3 on 2025-06-19 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AllPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('likes_count', models.PositiveBigIntegerField(default=0)),
                ('comments_count', models.PositiveBigIntegerField(default=0)),
                ('share_count', models.PositiveBigIntegerField(default=0)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AniPosts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
