# Generated by Django 5.2.3 on 2025-06-19 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allposts',
            name='avatar_url',
            field=models.URLField(default='static/images/img.png', max_length=300),
        ),
        migrations.AlterField(
            model_name='allposts',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
