# Generated by Django 5.2.3 on 2025-06-28 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_alter_allposts_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mal_id', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('image_url', models.URLField(blank=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'mal_id')},
            },
        ),
    ]
