# Generated by Django 5.2.3 on 2025-07-02 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cover_image',
            field=models.ImageField(default='profile_pics/cover_page.png', upload_to='profile_pics/'),
        ),
    ]
