# Generated by Django 5.2.3 on 2025-07-02 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_userprofile_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cover_image',
            field=models.ImageField(default='cover_pics/cover_page.png', upload_to='profile_pics/'),
        ),
    ]
