# Generated by Django 5.2.3 on 2025-07-08 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_userprofile_bio_userprofile_show_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.TextField(blank=True),
        ),
    ]
