# Generated by Django 5.2.3 on 2025-07-08 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0014_userprofile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='name',
        ),
    ]
