# Generated by Django 5.2.3 on 2025-07-09 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0015_remove_userprofile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='total_episodes',
            field=models.IntegerField(default=0),
        ),
    ]
