# Generated by Django 5.2.3 on 2025-08-16 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0017_alter_allposts_options_comment_commentlike_postlike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allposts',
            name='comments_count',
        ),
        migrations.AlterField(
            model_name='allposts',
            name='avatar_url',
            field=models.URLField(default='/static/images/img.png', max_length=300),
        ),
    ]
